### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by bobbui** [LogRocket/logrocket-react#23]
React 17 has been out for a while, Could u please add support for React 17 please?
Thanks

**Comment by rememberlenny** [comment]
Me too please

**Comment by jupardo** [comment]
Any update? Thank you in advance

**Comment by timonbimon** [comment]
+1

**Comment by FayP** [comment]
👍 Keen for this too please.

**Comment by scottwilson312** [comment]
A proposed timeline for this would be great. React's already at stable version 17.02, anyone starting a new react project would have to downgrade to use LogRocket.

Thanks!

**Comment by huksley** [comment]
@eranimo Any updates on this? React 17, is an incremental update over 16 and should not be too difficult to support.

**Comment by gustavopch** [comment]
This repo seems to be abandoned since 2019. I wonder why.

**Comment by nimas0** [comment]
Need update for 17! Please

**Comment by eranimo** [comment]
Hello everyone! Just wanted to let all you know that React 17 support is being investigated currently. Please note that this plugin always relied on an unofficial hook into the React internals, which is why it tends to break with new versions. This hook was changed in the new version and we are exploring alternatives.

**Comment by eranimo** [comment]
Please upgrade to `logrocket-react@5` for React 17 support.
